// Team profiles shown in the pop-up when a team card is clicked.
// Keyed by the alt text of the card's photo; bios follow the course faculty page (course.ccgh-idd.de)
// or, for non-faculty members, their CCGH staff pages and publications.
// Team members without an entry here keep a plain, non-clickable card.
window.teamData = {
    "Stefan Flasche": { topics: ["Vaccines", "Outbreak response", "Policy"], profileUrl: "https://globalhealth.charite.de/en/metas/person/person/address_detail/prof_dr_stefan_flasche/", bio: "Einstein Professor for Global Health and Infectious Disease Dynamics at the Charité Centre for Global Health and Professor for Vaccine Epidemiology at London School of Hygiene and Tropical Medicine. His research focuses mostly on optimising global immunisation strategies and a better understanding of infectious disease transmission dynamics, including in real-time during outbreaks." },
    "David Hodgson": { topics: ["Serology", "Transmission dynamics", "Vaccines"], profileUrl: "https://globalhealth.charite.de/en/metas/person/person/address_detail/dr_david_hodgson", bio: "Postdoctoral researcher at the Charité Centre for Global Health, developing models that integrate serological data, immunology, and epidemiology to inform vaccination policy. He completed his PhD at LSHTM on transmission modelling and cost-effectiveness of interventions against RSV, work that has informed national immunisation advisory groups." },
    "Billy John Quilty": { topics: ["Outbreak response", "Vaccines", "Transmission dynamics"], profileUrl: "https://globalhealth.charite.de/en/metas/person/person/address_detail/billy_quilty/", bio: "Researcher in infectious disease epidemiology and mathematical modelling at the Charité Centre for Global Health, with a PhD from LSHTM focused on modelling quarantine and testing strategies during the COVID-19 pandemic. His work spans vaccine impact evaluation and social contact pattern analysis, and he retains an honorary research fellowship at LSHTM." },
    "Matej Kriznar": { topics: ["Phylogenetics", "Data analytics", "Model evaluation"], profileUrl: "https://globalhealth.charite.de/en/metas/person/person/address_detail/matej_kriznar/", bio: "Researcher at the Charité Centre for Global Health working on computational modelling of historical population processes and the robustness of Bayesian phylogenetic methods. His background spans population genetics, computational social science, and pathogen genomics." },
    "Augustine Masinde": { topics: ["Vaccines", "Transmission dynamics", "Data analytics"], profileUrl: "https://globalhealth.charite.de/en/metas/person/person/address_detail/augustine_masinde_1/", bio: "Scientific assistant at the Charité Centre for Global Health, trained in mathematics and data science. His research uses mathematical modelling to optimise vaccination programmes for Chikungunya and other arboviruses in Kenya." },
    "Kaige Dong": { topics: ["Vaccines", "Transmission dynamics", "Data analytics"], profileUrl: "https://globalhealth.charite.de/en/metas/person/person/address_detail/kaige_dong_1/", bio: "PhD student specialising in vaccine epidemiology and mathematical modelling. His research focuses on pneumococcal conjugate vaccines and predicting serotype replacement in children." },
    "Dexin Gong": { topics: ["Model fitting", "Data analytics", "Transmission dynamics"], profileUrl: "https://internationale-gesundheit.charite.de/metas/person/person/address_detail/dexin_gong/", bio: "PhD student at the Charité Institute for International Health, contributing to teaching on model fitting and infectious disease modelling." },
    "Lukas Hemmers-Pauly": { topics: ["Outbreak response", "Transmission dynamics", "Data analytics"], profileUrl: "https://globalhealth.charite.de/en/metas/person/person/address_detail/lukas_hemmers_pauly/", bio: "Research associate at the Charité Centre for Global Health contributing to teaching on outbreak response and infectious disease modelling." },
    "Lucy Mbone Ingaiza": { topics: ["Serology", "Transmission dynamics", "Data analytics"], profileUrl: "https://globalhealth.charite.de/en/metas/person/person/address_detail/lucy_mbone_ingaiza_1/", bio: "PhD student in Health Data Sciences with a background in epidemiology, vaccine strategy, and HIV research. Her current work combines serological and surveillance data with mathematical modelling to study RSV in older adults in Germany." },
    "Julia Mayer": { topics: ["Vaccines", "Transmission dynamics", "Model choice"], profileUrl: "https://globalhealth.charite.de/en/metas/person/person/address_detail/julia_stephanie_mayer/", bio: "PhD researcher at the Charité Centre for Global Health, using mathematical modelling to determine optimal vaccination strategies against RSV in children in low- and middle-income countries. She holds a bachelor's degree in bioengineering from EPFL and an MSc in Epidemiology from LSHTM." },
    "Hugo Soubrier": { topics: ["Outbreak response", "Data analytics", "Transmission dynamics"], profileUrl: "https://globalhealth.charite.de/en/metas/person/person/address_detail/hugo_soubrier/", bio: "PhD candidate at the Charité Centre for Global Health, co-supervised by Prof. Stefan Flasche, Anton Camacho (Epicentre), and Olivier le Polain (WHO). His research applies mathematical and data analytics approaches to outbreak response and epidemiology workflows in humanitarian emergencies." },
    "Adriana Torres": { topics: ["Climate-sensitive models", "Transmission dynamics", "Model choice"], profileUrl: "https://internationale-gesundheit.charite.de/metas/person/person/address_detail/adriana_lucia_tibaduiza_torres/", bio: "PhD student at the Charité Institute for International Health and member of the Charité global health community, contributing to teaching on climate-sensitive infectious disease models." },
    "Rebecca Sophia Lais": { topics: ["Pandemic preparedness", "Modelling tools", "Policy"], profileUrl: "https://globalhealth.charite.de/en/metas/person/person/address_detail/rebecca_sophia_lais/", bio: "PhD student at the Charité Centre for Global Health. Her work looks at how epidemiological models and simulation tools can support public health decision-making, including a scoping review of open-source modelling tools for decision-makers during emerging pandemics and epidemics." },
    "Hendrik Oye": { topics: ["Project management", "Global health policy"], profileUrl: "https://globalhealth.charite.de/en/metas/person/person/address_detail/hendrik_oye/", bio: "Project Manager at the Charité Centre for Global Health, supporting the Infectious Disease Dynamics and Global Health Policy Lab groups. He has worked at the Global Fund in Geneva and the Deutsche Gesellschaft für Internationale Zusammenarbeit (GIZ) in Togo and Germany, and has a background in international and African studies from Leiden University and the University of Oxford." },
    "Michael Briga": { topics: ["Historical epidemiology", "Vaccines", "Seasonality"], profileUrl: "https://globalhealth.charite.de/en/metas/person/person/address_detail/michael_briga/", bio: "Evolutionary ecologist and infectious disease epidemiologist, docent at the University of Turku and guest researcher at the Charité Centre for Global Health. His work uses historical records and transmission models to study the dynamics of measles, pertussis and other childhood infections, including the effects of vaccination and of town size and structure on disease risk." },
    "Ayaka Monoi": { topics: ["RSV", "Vaccines", "Transmission dynamics"], profileUrl: "https://globalhealth.charite.de/en/metas/person/person/address_detail/ayaka_monoi/", bio: "Researcher at the Centre for Mathematical Modelling of Infectious Diseases at the London School of Hygiene & Tropical Medicine, with links to Nagasaki University, and guest researcher at the Charité Centre for Global Health. She models RSV immunisation strategies, including the benefits and risks of maternal RSV vaccination in South Africa and the optimal seasonal timing of infant immunisation in Japan." }
};
